# Generated by Django 5.2 on 2025-05-03 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinggoal",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="reading.readingplan",
            ),
        ),
    ]
