# Generated by Django 5.2 on 2025-04-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_image", models.URLField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=500)),
                ("source", models.CharField(default="manual", max_length=20)),
                (
                    "google_book_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("genre", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        null=True,
                    ),
                ),
                ("loaned_to", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "loaned_to_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_loaned", models.BooleanField(default=False)),
                ("is_wishlist", models.BooleanField(default=False)),
            ],
        ),
    ]
