# Generated by Django 5.2 on 2025-04-11 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_author_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="is_loaned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
