# Generated by Django 5.2 on 2025-04-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_date_added_book_due_date_book_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "★☆☆☆☆"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                ],
                null=True,
            ),
        ),
    ]
