# Generated by Django 5.2 on 2025-05-03 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("user", "google_book_id", "is_wishlist")},
        ),
    ]
