# Generated by Django 5.2 on 2025-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="google_book_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
