# Generated by Django 5.2 on 2025-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="google_book_id",
            field=models.CharField(blank=True, default="unknown", max_length=50),
        ),
    ]
