# Generated by Django 5.2 on 2025-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_date_added_book_genre_book_is_loaned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
