# Generated by Django 5.2 on 2025-04-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_google_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
