# Generated by Django 5.2 on 2025-04-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="library_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
