# Generated by Django 5.2 on 2025-04-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_library_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="loaned_to_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
