# Generated by Django 5.2 on 2025-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_total_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_wishlist",
            field=models.BooleanField(default=False),
        ),
    ]
