# Generated by Django 5.2 on 2025-04-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_loaned_to_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="loaned_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
