# Generated by Django 5.2 on 2025-04-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_book_is_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
